{
 "title": "T-RMM Agent Dashboard with Software",
 "tags": [ "TRMMAgentDashboard" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Client",
    "label": "Client",
    "query": "SELECT name FROM clients_client"
   },
   {
    "name": "Sites",
    "label": "Site",
    "query": "SELECT\n    clients_site.name\nFROM\n    clients_site\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n    clients_client.name IN ($Client)"
   },
   {
    "name": "Agent",
    "label": "Agent",
    "query": "SELECT\n  agents_agent.hostname || '(' || clients_client.name || '/' || clients_site.name || ')' AS __text,\n  agents_agent.agent_id AS __value\nFROM\n    agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)"
   },
   { "name": "Tactical", "query": "postgres" },
   { "name": "TacticalURL", "query": "rmm.example.com" },
   { "name": "GrafanaURL", "query": "grafana.example.com" }
  ]
 },
 "panels": [
  {
   "title": "Information of the selected agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  concat('Site: ',clients_site.name,' / HostName: ', agents_agent.hostname,' ',agents_agent.DESCRIPTION)\nfrom \n  agents_agent\n  LEFT OUTER JOIN clients_site on agents_agent.site_id = clients_site.id\n  where \n    agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "select   \r\nCASE\r\n  WHEN (count(*) = 1) THEN 'Connected'\r\n  WHEN (count(*) = 0) THEN 'Not Connected'\r\n  ELSE ''\r\n END AS modifiedpvc\r\n  \r\n from \r\n  agents_agent\r\n where \r\n   agents_agent.agent_id = '$Agent'  and\r\n   last_seen > NOW()- interval '1 hours'\r\n "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  concat(\r\n          to_char(now() - to_timestamp(boot_time) ,'DD' ),' Days ', \r\n          to_char(now() - to_timestamp(boot_time),'HH24' ), ' Hours ',\r\n          to_char(now() - to_timestamp(boot_time),'MI' ), ' Minutes '\r\n        )\r\nFrom \r\n  agents_agent\r\nWhere\r\n  agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Track CPU consumption for the selected agent.",
   "gridPos": { "h": 11, "w": 7, "x": 5, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  x AS \"time\",\r\n  y as \"CPU Load\"\r\n  FROM checks_checkhistory, checks_check, agents_agent\r\n  WHERE checks_checkhistory.agent_id=agents_agent.agent_id AND checks_checkhistory.check_id=checks_check.id\r\n  AND agents_agent.agent_id='$Agent' AND checks_check.check_type='cpuload'\r\n  AND x BETWEEN $__timeFrom() and $__timeTo()\r\n  ORDER BY x"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Track memory consumption for the selected agent.",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  x AS \"time\",\r\n  y as \"Memory Usage\"\r\nFROM \r\n  checks_checkhistory, checks_check, agents_agent\r\nWHERE \r\n  checks_checkhistory.agent_id=agents_agent.agent_id AND checks_checkhistory.check_id=checks_check.id\r\n    AND agents_agent.agent_id='$Agent' AND checks_check.check_type='memory'\r\n    AND x BETWEEN $__timeFrom() and $__timeTo()\r\n  ORDER BY x"
    }
   ]
  },
  {
   "title": "Drive Usage",
   "type": "timeseries",
   "description": "Track disk consumption for the selected agent.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  x AS \"time\",\r\n  y as \"Disk Usage\"\r\nFROM \r\n  checks_checkhistory, checks_check, agents_agent\r\nWHERE checks_checkhistory.agent_id=agents_agent.agent_id AND checks_checkhistory.check_id=checks_check.id\r\n    AND agents_agent.agent_id='$Agent' AND checks_check.check_type='diskspace'\r\n    AND x BETWEEN $__timeFrom() and $__timeTo()\r\n  ORDER BY x"
    }
   ]
  },
  {
   "title": "CPU Model",
   "type": "stat",
   "description": "Type of CPU installed",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select  \n  wmi_detail,\n  CASE \n    WHEN wmi_detail->'cpu' IS NOT NULL\n    THEN concat(wmi_detail->'cpu'->0->0->>'Name',' \\ ',wmi_detail->'base_board'->0->0->>'Manufacturer')\n    ELSE concat(wmi_detail->'cpus'->>0)\n  END\nfrom \n  agents_agent\nwhere \n   agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select   \r\nSUBSTRING(agents_agent.operating_system,'(.*)(?:,|x86_64)')\r\n  \r\nfrom \r\n  agents_agent\r\nwhere \r\n     agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 3, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE WHEN EXISTS \n    (\n        SELECT * FROM public.winupdate_winupdate WHERE action='approve' AND installed='False' AND agent_id=(SELECT id FROM agents_agent where agents_agent.agent_id = '$Agent')\n    )\n    THEN 'Windows not up to date'\n    ELSE 'Windows up to date'\nEND AS  Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 3, "y": 7 },
   "targets": [
    {
     "rawSql": "select\n  CASE\n   WHEN (agents_agent.needs_reboot = true) THEN 'Reboot required'\n    WHEN (agents_agent.needs_reboot = false) THEN 'No reboot required'\n  ELSE 'nothing'\n END AS  Status\nFrom \n  agents_agent\nWhere\n  agents_agent.agent_id = '$Agent'\n"
    }
   ]
  },
  {
   "title": "System Ram",
   "type": "stat",
   "description": "Total Agent Memory",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select   \r\n   concat((total_ram),'GB / ',concat(wmi_detail->'mem'->0->0->>'Speed','MHz'))\r\n  \r\nfrom \r\n  agents_agent\r\nwhere \r\n  agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "table",
   "description": "Total free disk space",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 8 },
   "targets": [
    {
     "rawSql": "select \r\n  concat(items.device,'\\ ', items.free,' free on ',items.total)\r\nfrom \r\n  agents_agent,\r\n  jsonb_to_recordset(disks) as items(device text, free text, total text)\r\nWhere\r\n  agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\r\n  disks->0->>'percent' as \"Occupation\"\r\nfrom \r\n  agents_agent\r\nwhere \r\n  agents_agent.agent_id = '$Agent'\r\n"
    }
   ]
  },
  {
   "title": "Software",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  jsonb_array_elements(software) -> 'name' AS \"Name\",\r\n  jsonb_array_elements(software) -> 'version' AS \"Version\",\r\n  jsonb_array_elements(software) -> 'uninstall' AS \"Uninstall\"\r\nFROM software_installedsoftware, agents_agent  \r\nWHERE software_installedsoftware.agent_id=agents_agent.id\r\n  AND agents_agent.agent_id ='$Agent'\r\n"
    }
   ]
  }
 ]
}