{
 "title": "T-RMM Dashboard with Software",
 "tags": [ "TRMMAgentDashboard" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Tactical", "query": "postgres" },
   { "name": "TacticalURL", "query": "rmm.example.com" },
   { "name": "GrafanaURL", "query": "grafana.example.com" }
  ]
 },
 "panels": [
  {
   "title": "Information on Client or selected site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Agents",
   "type": "stat",
   "description": "Agents at selected clients/sites",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM agents_agent\nwhere \n  site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Information Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n    OR checks_check.agent_id = agents_agent.id\n    OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\n  WHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)\n    AND alerts_alert.severity = 'info'\n    AND alerts_alert.resolved = false\n  ),\n  ' / ',\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n  WHERE\n    alerts_alert.severity = 'info'\n    AND alerts_alert.resolved = false\n  )\n)"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n    OR checks_check.agent_id = agents_agent.id\n    OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\n  WHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)\n    AND alerts_alert.severity = 'warning'\n    AND alerts_alert.resolved = false\n  ),\n  ' / ',\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n  WHERE\n    alerts_alert.severity = 'warning'\n    AND alerts_alert.resolved = false\n  )\n)"
    }
   ]
  },
  {
   "title": "Error Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n    OR checks_check.agent_id = agents_agent.id\n    OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\n  WHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)\n    AND alerts_alert.severity = 'error'\n    AND alerts_alert.resolved = false\n  ),\n  ' / ',\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n  WHERE\n    alerts_alert.severity = 'error'\n    AND alerts_alert.resolved = false\n  )\n)"
    }
   ]
  },
  {
   "title": "OS Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "  select (\r\nSELECT\r\n  count(*)\r\n  FROM agents_agent\r\nWhere\r\n  SUBSTRING(agents_agent.operating_system,POSITION(',' in agents_agent.operating_system)+2,2) = '64' and\r\n  site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\r\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))) as \"64 Bit\",\r\n\r\n  (SELECT\r\n  count(*)\r\n  FROM agents_agent\r\nWhere\r\n  SUBSTRING(agents_agent.operating_system,POSITION(',' in agents_agent.operating_system)+2,2) = '32' and\r\n   site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\r\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))) as \"32 Bit\" "
    }
   ]
  },
  {
   "title": "OS Type",
   "type": "table",
   "description": "List all OS installed",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(*) as \"count\",\r\n  SUBSTRING(agents_agent.operating_system,'(.*)(?:,|x86_64)') AS \"Operating System\"\r\nFROM agents_agent\r\n  INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\r\n  INNER JOIN clients_client ON clients_site.client_id = clients_client.id\r\nWHERE\r\n  clients_client.name IN ($Client)\r\n  AND clients_site.name IN ($Sites)\r\nGroup by \"Operating System\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  {
   "title": "Type of CPUs",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n    count(*) as \"count\",\n    (CASE \n      WHEN wmi_detail->'cpu' IS NOT NULL\n      THEN SUBSTRING(agents_agent.wmi_detail->'cpu'->0->0->>'Name','(?:AMD|Intel\\(R\\)|Intel)(.*)(?:@|Processor|with)')\n      ELSE SUBSTRING(agents_agent.wmi_detail->'cpus'->>0,'(?:AMD|Intel\\(R\\)|Intel)(.*)(?:@|Processor|with)')\n    END) as \"CPU Name\"\nFROM agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n  clients_client.name IN ($Client)\n  AND clients_site.name IN ($Sites)\nGroup by \"CPU Name\"\nOrder by \"count\" desc"
    }
   ]
  },
  {
   "title": "Installed System RAM",
   "type": "table",
   "description": "List all installed memory",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
   "targets": [
    {
     "rawSql": "  SELECT \r\n  count(*) as \"count\",\r\n  concat((total_ram),' GB') as \"Size Memory\"\r\n  FROM agents_agent\r\nINNER JOIN clients_site on site_id = clients_site.id\r\nWHERE site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\r\nAND site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites)))\r\nGroup by \"Size Memory\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  {
   "title": "Agent Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n  clients_site.name AS \"Site\",\n  hostname AS \"Hostname\",\n  agents_agent.agent_id,\n  'https://docs.tacticalrmm.com/images/favicon.ico' as \"RMM\",\n  'https://grafana.com/static/assets/img/fav32.png' as \"Stats\",\n  (\n        CASE\n            WHEN last_seen > NOW() - interval '1 minute' THEN 'Online'\n            ELSE 'Offline'\n        END\n    ) AS \"Status\",\n  last_seen as \"Last Response\",\n  to_timestamp(boot_time) AS \"Last Reboot\"\nFROM agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)"
    }
   ]
  },
  {
   "title": "Error Messages",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n    alerts_alert.alert_time as \"Date\",\n    alerts_alert.message as \"Message\",\n    agents_agent.agent_id,\n    'https://docs.tacticalrmm.com/images/favicon.ico' as \"RMM\"\nFROM alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n                            OR checks_check.agent_id = agents_agent.id\n                            OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n  clients_client.name IN ($Client)\n  AND clients_site.name IN ($Sites)\n  AND alerts_alert.severity = 'error' \n  AND alerts_alert.resolved = false"
    }
   ]
  },
  {
   "title": "All Software",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CONCAT(\r\n    'Computer - ',\r\n    agents_agent.hostname,' ',agents_agent.DESCRIPTION,' -  '\r\n    'Software - ',\r\n    jsonb_array_elements(software) -> 'name',\r\n    ' - Version - ',\r\n    jsonb_array_elements(software) -> 'version',\r\n     '  - Uninstall   -',\r\n    jsonb_array_elements(software) -> 'uninstall' \r\n  ) AS \"All Software\"\r\nFROM software_installedsoftware, agents_agent  \r\n\r\nWHERE software_installedsoftware.agent_id=agents_agent.id\r\n  LIMIT ALL"
    }
   ]
  }
 ]
}