{
 "title": "T-RMM Agent Dashboard with Software",
 "tags": [ "TRMMAgentDashboard" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Client",
    "label": "Client",
    "query": "SELECT name FROM clients_client"
   },
   {
    "name": "Sites",
    "label": "Site",
    "query": "SELECT\n    clients_site.name\nFROM\n    clients_site\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n    clients_client.name IN ($Client)"
   },
   {
    "name": "Agent",
    "label": "Agent",
    "query": "SELECT\n  agents_agent.hostname || '(' || clients_client.name || '/' || clients_site.name || ')' AS __text,\n  agents_agent.agent_id AS __value\nFROM\n    agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)"
   },
   { "name": "Tactical", "query": "postgres" },
   { "name": "TacticalURL", "query": "rmm.example.com" },
   { "name": "GrafanaURL", "query": "grafana.example.com" }
  ]
 },
 "panels": [
  {
   "title": "Information of the selected agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  concat('Site: ',clients_site.name,' / HostName: ', agents_agent.hostname,' ',agents_agent.DESCRIPTION)\nfrom \n  agents_agent\n  LEFT OUTER JOIN clients_site on agents_agent.site_id = clients_site.id\n  where \n    agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "select   \r\nCASE\r\n  WHEN (count(*) = 1) THEN 'Connected'\r\n  WHEN (count(*) = 0) THEN 'Not Connected'\r\n  ELSE ''\r\n END AS modifiedpvc\r\n  \r\n from \r\n  agents_agent\r\n where \r\n   agents_agent.agent_id = '$Agent'  and\r\n   last_seen > NOW()- interval '1 hours'\r\n "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  concat(\r\n          to_char(now() - to_timestamp(boot_time) ,'DD' ),' Days ', \r\n          to_char(now() - to_timestamp(boot_time),'HH24' ), ' Hours ',\r\n          to_char(now() - to_timestamp(boot_time),'MI' ), ' Minutes '\r\n        )\r\nFrom \r\n  agents_agent\r\nWhere\r\n  agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Track CPU consumption for the selected agent.",
   "gridPos": { "h": 11, "w": 7, "x": 5, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  x AS \"time\",\r\n  y as \"CPU Load\"\r\n  FROM checks_checkhistory, checks_check, agents_agent\r\n  WHERE checks_checkhistory.agent_id=agents_agent.agent_id AND checks_checkhistory.check_id=checks_check.id\r\n  AND agents_agent.agent_id='$Agent' AND checks_check.check_type='cpuload'\r\n  AND x BETWEEN $__timeFrom() and $__timeTo()\r\n  ORDER BY x"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Track memory consumption for the selected agent.",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  x AS \"time\",\r\n  y as \"Memory Usage\"\r\nFROM \r\n  checks_checkhistory, checks_check, agents_agent\r\nWHERE \r\n  checks_checkhistory.agent_id=agents_agent.agent_id AND checks_checkhistory.check_id=checks_check.id\r\n    AND agents_agent.agent_id='$Agent' AND checks_check.check_type='memory'\r\n    AND x BETWEEN $__timeFrom() and $__timeTo()\r\n  ORDER BY x"
    }
   ]
  },
  {
   "title": "Drive Usage",
   "type": "timeseries",
   "description": "Track disk consumption for the selected agent.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  x AS \"time\",\r\n  y as \"Disk Usage\"\r\nFROM \r\n  checks_checkhistory, checks_check, agents_agent\r\nWHERE checks_checkhistory.agent_id=agents_agent.agent_id AND checks_checkhistory.check_id=checks_check.id\r\n    AND agents_agent.agent_id='$Agent' AND checks_check.check_type='diskspace'\r\n    AND x BETWEEN $__timeFrom() and $__timeTo()\r\n  ORDER BY x"
    }
   ]
  },
  {
   "title": "CPU Model",
   "type": "stat",
   "description": "Type of CPU installed",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select  \n  wmi_detail,\n  CASE \n    WHEN wmi_detail->'cpu' IS NOT NULL\n    THEN concat(wmi_detail->'cpu'->0->0->>'Name',' \\ ',wmi_detail->'base_board'->0->0->>'Manufacturer')\n    ELSE concat(wmi_detail->'cpus'->>0)\n  END\nfrom \n  agents_agent\nwhere \n   agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select   \r\nSUBSTRING(agents_agent.operating_system,'(.*)(?:,|x86_64)')\r\n  \r\nfrom \r\n  agents_agent\r\nwhere \r\n     agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 3, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n    CASE WHEN EXISTS \n    (\n        SELECT * FROM public.winupdate_winupdate WHERE action='approve' AND installed='False' AND agent_id=(SELECT id FROM agents_agent where agents_agent.agent_id = '$Agent')\n    )\n    THEN 'Windows not up to date'\n    ELSE 'Windows up to date'\nEND AS  Status"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 3, "y": 7 },
   "targets": [
    {
     "rawSql": "select\n  CASE\n   WHEN (agents_agent.needs_reboot = true) THEN 'Reboot required'\n    WHEN (agents_agent.needs_reboot = false) THEN 'No reboot required'\n  ELSE 'nothing'\n END AS  Status\nFrom \n  agents_agent\nWhere\n  agents_agent.agent_id = '$Agent'\n"
    }
   ]
  },
  {
   "title": "System Ram",
   "type": "stat",
   "description": "Total Agent Memory",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select   \r\n   concat((total_ram),'GB / ',concat(wmi_detail->'mem'->0->0->>'Speed','MHz'))\r\n  \r\nfrom \r\n  agents_agent\r\nwhere \r\n  agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "table",
   "description": "Total free disk space",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 8 },
   "targets": [
    {
     "rawSql": "select \r\n  concat(items.device,'\\ ', items.free,' free on ',items.total)\r\nfrom \r\n  agents_agent,\r\n  jsonb_to_recordset(disks) as items(device text, free text, total text)\r\nWhere\r\n  agents_agent.agent_id = '$Agent'"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select\r\n  disks->0->>'percent' as \"Occupation\"\r\nfrom \r\n  agents_agent\r\nwhere \r\n  agents_agent.agent_id = '$Agent'\r\n"
    }
   ]
  },
  {
   "title": "Software",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  jsonb_array_elements(software) -> 'name' AS \"Name\",\r\n  jsonb_array_elements(software) -> 'version' AS \"Version\",\r\n  jsonb_array_elements(software) -> 'uninstall' AS \"Uninstall\"\r\nFROM software_installedsoftware, agents_agent  \r\nWHERE software_installedsoftware.agent_id=agents_agent.id\r\n  AND agents_agent.agent_id ='$Agent'\r\n"
    }
   ]
  },
  {
   "title": "Software",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CONCAT(\r\n    'Name - ',\r\n    jsonb_array_elements(software) -> 'name',\r\n    ' - Version - ',\r\n    jsonb_array_elements(software) -> 'version',\r\n     '  - Uninstall   -',\r\n    jsonb_array_elements(software) -> 'uninstall' \r\n  ) AS \"Software\"\r\nFROM software_installedsoftware, agents_agent  \r\nWHERE software_installedsoftware.agent_id=agents_agent.id\r\n  AND agents_agent.agent_id ='$Agent'\r\n"
    }
   ]
  },
  {
   "title": "Information on Client or selected site",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Agents",
   "type": "stat",
   "description": "Agents at selected clients/sites",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM agents_agent\nwhere \n  site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Information Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n    OR checks_check.agent_id = agents_agent.id\n    OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\n  WHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)\n    AND alerts_alert.severity = 'info'\n    AND alerts_alert.resolved = false\n  ),\n  ' / ',\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n  WHERE\n    alerts_alert.severity = 'info'\n    AND alerts_alert.resolved = false\n  )\n)"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n    OR checks_check.agent_id = agents_agent.id\n    OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\n  WHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)\n    AND alerts_alert.severity = 'warning'\n    AND alerts_alert.resolved = false\n  ),\n  ' / ',\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n  WHERE\n    alerts_alert.severity = 'warning'\n    AND alerts_alert.resolved = false\n  )\n)"
    }
   ]
  },
  {
   "title": "Error Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT CONCAT(\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n    OR checks_check.agent_id = agents_agent.id\n    OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\n  WHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)\n    AND alerts_alert.severity = 'error'\n    AND alerts_alert.resolved = false\n  ),\n  ' / ',\n  (SELECT\n    count(*)\n  FROM\n    alerts_alert\n  WHERE\n    alerts_alert.severity = 'error'\n    AND alerts_alert.resolved = false\n  )\n)"
    }
   ]
  },
  {
   "title": "OS Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "  select (\r\nSELECT\r\n  count(*)\r\n  FROM agents_agent\r\nWhere\r\n  SUBSTRING(agents_agent.operating_system,POSITION(',' in agents_agent.operating_system)+2,2) = '64' and\r\n  site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\r\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))) as \"64 Bit\",\r\n\r\n  (SELECT\r\n  count(*)\r\n  FROM agents_agent\r\nWhere\r\n  SUBSTRING(agents_agent.operating_system,POSITION(',' in agents_agent.operating_system)+2,2) = '32' and\r\n   site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites))) and\r\n  site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))) as \"32 Bit\" "
    }
   ]
  },
  {
   "title": "OS Type",
   "type": "table",
   "description": "List all OS installed",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  count(*) as \"count\",\r\n  SUBSTRING(agents_agent.operating_system,'(.*)(?:,|x86_64)') AS \"Operating System\"\r\nFROM agents_agent\r\n  INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\r\n  INNER JOIN clients_client ON clients_site.client_id = clients_client.id\r\nWHERE\r\n  clients_client.name IN ($Client)\r\n  AND clients_site.name IN ($Sites)\r\nGroup by \"Operating System\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  {
   "title": "Type of CPUs",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT \n    count(*) as \"count\",\n    (CASE \n      WHEN wmi_detail->'cpu' IS NOT NULL\n      THEN SUBSTRING(agents_agent.wmi_detail->'cpu'->0->0->>'Name','(?:AMD|Intel\\(R\\)|Intel)(.*)(?:@|Processor|with)')\n      ELSE SUBSTRING(agents_agent.wmi_detail->'cpus'->>0,'(?:AMD|Intel\\(R\\)|Intel)(.*)(?:@|Processor|with)')\n    END) as \"CPU Name\"\nFROM agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n  clients_client.name IN ($Client)\n  AND clients_site.name IN ($Sites)\nGroup by \"CPU Name\"\nOrder by \"count\" desc"
    }
   ]
  },
  {
   "title": "Installed System RAM",
   "type": "table",
   "description": "List all installed memory",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 43 },
   "targets": [
    {
     "rawSql": "  SELECT \r\n  count(*) as \"count\",\r\n  concat((total_ram),' GB') as \"Size Memory\"\r\n  FROM agents_agent\r\nINNER JOIN clients_site on site_id = clients_site.id\r\nWHERE site_id IN (SELECT id FROM clients_site WHERE client_id IN (SELECT id FROM clients_client WHERE name IN ($Client)))\r\nAND site_id IN (SELECT id FROM clients_site WHERE site_id IN (SELECT id FROM clients_site WHERE name IN ($Sites)))\r\nGroup by \"Size Memory\"\r\nOrder by \"count\" desc\r\n  "
    }
   ]
  },
  {
   "title": "Agent Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT \n  clients_site.name AS \"Site\",\n  hostname AS \"Hostname\",\n  agents_agent.agent_id,\n  'https://docs.tacticalrmm.com/images/favicon.ico' as \"RMM\",\n  'https://grafana.com/static/assets/img/fav32.png' as \"Stats\",\n  (\n        CASE\n            WHEN last_seen > NOW() - interval '1 minute' THEN 'Online'\n            ELSE 'Offline'\n        END\n    ) AS \"Status\",\n  last_seen as \"Last Response\",\n  to_timestamp(boot_time) AS \"Last Reboot\"\nFROM agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n    clients_client.name IN ($Client)\n    AND clients_site.name IN ($Sites)"
    }
   ]
  },
  {
   "title": "Error Messages",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT \n    alerts_alert.alert_time as \"Date\",\n    alerts_alert.message as \"Message\",\n    agents_agent.agent_id,\n    'https://docs.tacticalrmm.com/images/favicon.ico' as \"RMM\"\nFROM alerts_alert\n    LEFT JOIN checks_check on alerts_alert.assigned_check_id = checks_check.id\n    LEFT JOIN autotasks_automatedtask on alerts_alert.assigned_task_id = autotasks_automatedtask.id\n    INNER JOIN agents_agent ON autotasks_automatedtask.agent_id = agents_agent.id\n                            OR checks_check.agent_id = agents_agent.id\n                            OR alerts_alert.agent_id = agents_agent.id\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n  clients_client.name IN ($Client)\n  AND clients_site.name IN ($Sites)\n  AND alerts_alert.severity = 'error' \n  AND alerts_alert.resolved = false"
    }
   ]
  }
 ]
}